spring:
  application:
    name: ms-employee
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cjavadatabase

server:
  port: 9006

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
            defaultZone: http://servicio-eureka-server:8761/eureka/
  instance:
    hostname: localhost 
    
configuracion:
  texto: Configurando ambiente desarrollo mongodb
